
"""
Interactive Chat Interface for RAG Complaint Chatbot
Using Gradio for web interface
"""

import gradio as gr
import pandas as pd
import numpy as np
import os
import json
from datetime import datetime
from typing import List, Dict, Tuple, Any
import sys

# Import our RAG pipeline
sys.path.append('src')
try:
    from rag_pipeline import RAGPipeline
except ImportError:
    # Create a simplified version if import fails
    class RAGPipeline:
        def __init__(self):
            self.initialized = False
            
        def load_vector_store(self):
            self.initialized = True
            return True
            
        def run_rag_pipeline(self, question):
            return {
                "question": question,
                "answer": f"Sample answer for: {question}\n\nThis is a placeholder response. "
                         "In production, this would be generated by the RAG pipeline.",
                "contexts": ["Sample context 1", "Sample context 2"],
                "sources": [
                    {"product": "Credit Card", "excerpt_preview": "Sample complaint about credit card..."},
                    {"product": "Personal Loan", "excerpt_preview": "Sample complaint about personal loan..."}
                ]
            }

class ComplaintChatbot:
    """Main chatbot application class"""
    
    def __init__(self, vector_store_path: str = "vector_store"):
        """
        Initialize chatbot
        
        Args:
            vector_store_path: Path to vector store
        """
        self.vector_store_path = vector_store_path
        self.rag_pipeline = None
        self.chat_history = []
        self.initialize_pipeline()
    
    def initialize_pipeline(self):
        """Initialize RAG pipeline"""
        try:
            print("Initializing RAG Pipeline...")
            self.rag_pipeline = RAGPipeline(
                vector_store_path=self.vector_store_path,
                embedding_model_name="all-MiniLM-L6-v2",
                llm_model_name="microsoft/DialoGPT-small"
            )
            
            # Load vector store
            if self.rag_pipeline.load_vector_store():
                # Initialize LLM
                self.rag_pipeline.initialize_llm(use_simple=True)
                print("RAG Pipeline initialized successfully!")
            else:
                print("Warning: Using demo mode (vector store not found)")
        
        except Exception as e:
            print(f"Error initializing pipeline: {e}")
            print("Running in demo mode...")
            self.rag_pipeline = RAGPipeline()  # Use dummy pipeline
    
    def process_query(self, query: str, history: List[Dict[str, str]] = None) -> Tuple[str, List[Dict[str, str]], str]:
        if not query or query.strip() == "":
            return "", history or [], ""
        
        if history is None:
            history = []

        try:
            # Run RAG pipeline
            result = self.rag_pipeline.run_rag_pipeline(query)
            answer = result['answer']
            sources = result.get('sources', [])

            # Format sources for display
            sources_html = self._format_sources_html(sources)

            # FIX: Update history using dicts with 'role' and 'content'
            updated_history = history + [
                {"role": "user", "content": query},
                {"role": "assistant", "content": answer}
            ]

            # Log interaction
            self._log_interaction(query, answer, sources)

            return "", updated_history, sources_html

        except Exception as e:
            fallback_answer = "I apologize, but I encountered an error processing your question. Please try rephrasing or ask about common complaint topics like credit cards or personal loans."
            updated_history = history + [
                {"role": "user", "content": query},
                {"role": "assistant", "content": fallback_answer}
            ]
            return "", updated_history, "<p>Unable to retrieve sources due to error.</p>"
    
    def _format_sources_html(self, sources: List[Dict]) -> str:
        """
        Format sources as HTML for display
        
        Args:
            sources: List of source dictionaries
            
        Returns:
            HTML string
        """
        if not sources:
            return "<p>No sources retrieved for this query.</p>"
        
        html = "<div style='margin-top: 20px; padding: 15px; background-color: #f5f5f5; border-radius: 5px;'>"
        html += "<h4 style='margin-top: 0; color: #333;'>📚 Sources Used:</h4>"
        
        for i, source in enumerate(sources[:3]):  # Show max 3 sources
            product = source.get('product', 'Unknown Product')
            excerpt = source.get('excerpt_preview', 'No excerpt available')
            
            html += f"""
            <div style='margin-bottom: 10px; padding: 10px; background-color: white; border-left: 4px solid #4CAF50;'>
                <strong>Source {i+1} ({product})</strong>
                <p style='margin: 5px 0; font-size: 0.9em; color: #666;'>{excerpt}</p>
            </div>
            """
        
        html += "</div>"
        return html
    
    def _log_interaction(self, query: str, answer: str, sources: List[Dict]):
        """Log user interaction for analysis"""
        log_entry = {
            "timestamp": datetime.now().isoformat(),
            "query": query,
            "answer_preview": answer[:100],
            "num_sources": len(sources),
            "sources_products": [s.get('product', 'Unknown') for s in sources]
        }
        
        self.chat_history.append(log_entry)
        
        # Save log periodically
        if len(self.chat_history) % 5 == 0:
            self._save_chat_log()
    
    def _save_chat_log(self):
        """Save chat log to file"""
        os.makedirs('data/processed', exist_ok=True)
        log_path = 'data/processed/chat_log.json'
        
        try:
            with open(log_path, 'w') as f:
                json.dump(self.chat_history, f, indent=2)
        except:
            pass  # Silent fail for logging
    
    def clear_chat(self):
        """Clear chat history"""
        self.chat_history = []
        return [], ""  # Return empty history and sources

def create_gradio_interface():
    """Create Gradio interface for the chatbot"""
    
    # Initialize chatbot
    chatbot = ComplaintChatbot()
    
    # Define CSS for styling
    css = """
    .gradio-container {
        max-width: 800px !important;
        margin: auto !important;
    }
    .chatbot {
        min-height: 400px;
        max-height: 500px;
        overflow-y: auto;
    }
    .sources-container {
        max-height: 300px;
        overflow-y: auto;
        border: 1px solid #ddd;
        padding: 15px;
        margin-top: 20px;
    }
    """
    
    # Define custom theme
    theme = gr.themes.Soft(
        primary_hue="green",
        secondary_hue="blue",
    ).set(
        button_primary_background_fill="#4CAF50",
        button_primary_background_fill_hover="#45a049",
        button_primary_text_color="white",
    )
    
    with gr.Blocks(theme=theme, css=css, title="CrediTrust Complaint Analyst") as demo:
        
        # Header
        gr.Markdown("""
        # 🏦 CrediTrust Complaint Analyst
        ### AI-Powered Financial Complaint Analysis
        
        This chatbot analyzes customer complaints to provide insights about financial products.
        It uses Retrieval-Augmented Generation (RAG) to ground responses in actual complaint data.
        
        **Try asking about:**
        - Common credit card issues
        - Personal loan complaints  
        - Savings account problems
        - Money transfer concerns
        """)
        
        # Store chat history in state
        chat_state = gr.State([])
        
        # Chatbot interface
        with gr.Row():
            with gr.Column(scale=2):
                # Chat history display
                chatbot_display = gr.Chatbot(
                    label="Conversation",
                    elem_classes="chatbot",
                    height=400,
                    value=[]
                )
                
                # Sources display
                sources_display = gr.HTML(
                    label="Sources",
                    elem_classes="sources-container"
                )
            
            with gr.Column(scale=1):
                # Stats and info panel
                gr.Markdown("### ℹ️ Information")
                
                with gr.Accordion("About this system", open=False):
                    gr.Markdown("""
                    **How it works:**
                    1. Your question is converted to embeddings
                    2. Similar complaint excerpts are retrieved
                    3. An LLM generates an answer based on retrieved context
                    
                    **Data Sources:**
                    - CFPB Consumer Complaint Database
                    - Filtered for 4 financial products
                    - 10,000+ complaint narratives
                    
                    **Models Used:**
                    - Embeddings: all-MiniLM-L6-v2
                    - LLM: DialoGPT-small
                    - Vector Store: FAISS
                    """)
                
                # Example questions
                with gr.Accordion("💡 Example Questions", open=True):
                    gr.Markdown("Click any question below to try it:")
                    
                    # Create example questions
                    example_questions = [
                        "What are common credit card complaints?",
                        "Tell me about personal loan issues",
                        "How do customers complain about savings accounts?",
                        "What problems occur with money transfers?"
                    ]
                    
                    # FIXED: Use gr.Examples correctly
                    gr.Examples(
                        examples=[[q] for q in example_questions],
                        inputs=[gr.Textbox(visible=False)],
                        fn=lambda x: x,
                        outputs=[gr.Textbox(visible=False)],
                        label=""
                    )
        
        # Input area
        with gr.Row():
            query_input = gr.Textbox(
                label="Ask a question about financial complaints",
                placeholder="Type your question here...",
                lines=2,
                scale=4,
                elem_id="query_input"
            )
            
            submit_btn = gr.Button(
                "Ask",
                variant="primary",
                scale=1
            )
        
        # Control buttons
        with gr.Row():
            clear_btn = gr.Button("Clear Chat", variant="secondary")
        
        # Function to handle query submission
        def submit_query(query: str, history: List[List[str]]) -> Tuple[str, List[List[str]], str]:
            """
            Process query and return updated chat history
            
            Args:
                query: User's question
                history: Current chat history
                
            Returns:
                Tuple of (cleared_input, updated_history, sources_html)
            """
            
            if not query or query.strip() == "":
                return "", history, ""
            
            # Process the query
            _, updated_history, sources_html = chatbot.process_query(query, history)
            return "", updated_history, sources_html
        
        # Connect components
        query_input.submit(
            submit_query,
            inputs=[query_input, chatbot_display],
            outputs=[query_input, chatbot_display, sources_display]
        )
        
        submit_btn.click(
            submit_query,
            inputs=[query_input, chatbot_display],
            outputs=[query_input, chatbot_display, sources_display]
        )
        
        # Clear button
        def clear_interface():
            chatbot.clear_chat()
            return [], ""
        
        clear_btn.click(
            clear_interface,
            outputs=[chatbot_display, sources_display]
        )
        
        # Footer
        gr.Markdown("""
        ---
        <div style="text-align: center; color: #666; font-size: 0.9em;">
        <p>⚠️ <strong>Disclaimer:</strong> This is a demonstration system. Responses are generated based on complaint data and may not represent complete or current information.</p>
        <p>For official financial advice, consult a qualified professional.</p>
        </div>
        """)
    
    return demo

def create_streamlit_app():
    """Alternative Streamlit implementation"""
    import streamlit as st
    
    st.set_page_config(
        page_title="CrediTrust Complaint Analyst",
        page_icon="🏦",
        layout="wide"
    )
    
    # Initialize chatbot
    if 'chatbot' not in st.session_state:
        st.session_state.chatbot = ComplaintChatbot()
        st.session_state.messages = []
        st.session_state.sources = ""
    
    # Header
    st.title("🏦 CrediTrust Complaint Analyst")
    st.markdown("### AI-Powered Financial Complaint Analysis")
    
    # Sidebar
    with st.sidebar:
        st.header("ℹ️ Information")
        
        with st.expander("How it works"):
            st.markdown("""
            1. **Query Processing**: Your question is converted to embeddings
            2. **Context Retrieval**: Similar complaint excerpts are retrieved
            3. **Answer Generation**: LLM generates answer based on context
            """)
        
        with st.expander("Example Questions"):
            examples = [
                "What are common credit card complaints?",
                "Tell me about personal loan issues",
                "How do customers complain about savings accounts?",
                "What problems occur with money transfers?"
            ]
            
            for example in examples:
                if st.button(example, key=example):
                    st.session_state.user_query = example
        
        st.markdown("---")
        st.markdown("**Models Used:**")
        st.markdown("- Embeddings: all-MiniLM-L6-v2")
        st.markdown("- LLM: DialoGPT-small")
        st.markdown("- Vector Store: FAISS")
        
        if st.button("Clear Chat", type="secondary"):
            st.session_state.messages = []
            st.session_state.sources = ""
            st.rerun()
    
    # Main chat area
    col1, col2 = st.columns([2, 1])
    
    with col1:
        # Chat display
        chat_container = st.container(height=500)
        
        with chat_container:
            for message in st.session_state.messages:
                with st.chat_message(message["role"]):
                    st.markdown(message["content"])
        
        # Input area
        user_query = st.chat_input("Ask about financial complaints...")
        
        if user_query:
            # Add user message
            st.session_state.messages.append({"role": "user", "content": user_query})
            
            # Get response
            answer, _, sources_html = st.session_state.chatbot.process_query(
                user_query, 
                []
            )
            
            # Add assistant message
            st.session_state.messages.append({"role": "assistant", "content": answer})
            st.session_state.sources = sources_html
            
            st.rerun()
    
    with col2:
        # Sources display
        st.subheader("📚 Sources")
        
        if st.session_state.sources:
            st.markdown(st.session_state.sources, unsafe_allow_html=True)
        else:
            st.info("No sources retrieved yet. Ask a question to see sources.")
        
        # Statistics
        st.markdown("---")
        st.subheader("📊 Statistics")
        
        if st.session_state.chatbot.chat_history:
            st.metric("Questions Asked", len(st.session_state.chatbot.chat_history))
            st.metric("Current Session", len(st.session_state.messages) // 2)
        else:
            st.metric("Questions Asked", 0)

def main():
    """Main entry point"""
    import argparse
    
    parser = argparse.ArgumentParser(description="RAG Complaint Chatbot")
    parser.add_argument("--ui", choices=["gradio", "streamlit"], default="gradio",
                       help="UI framework to use (default: gradio)")
    parser.add_argument("--port", type=int, default=7860,
                       help="Port to run the server on (default: 7860)")
    parser.add_argument("--share", action="store_true",
                       help="Create a public link (Gradio only)")
    
    args = parser.parse_args()
    
    print("="*80)
    print("RAG COMPLAINT CHATBOT - INTERACTIVE INTERFACE")
    print("="*80)
    
    if args.ui == "gradio":
        print(f"\nLaunching Gradio interface on port {args.port}...")
        print("Press Ctrl+C to stop the server")
        
        demo = create_gradio_interface()
        demo.launch(
            server_name="127.0.0.1",
            server_port=args.port,
            share=args.share,
            show_error=True
        )
    
    elif args.ui == "streamlit":
        print("\nTo run Streamlit app, use: streamlit run app.py -- --ui streamlit")
        print("Or run this script with Streamlit directly.")
        
        # Note: Streamlit needs to be run differently
        import subprocess
        subprocess.run(["streamlit", "run", __file__, "--", "--ui", "streamlit"])

if __name__ == "__main__":
    # Check if running with streamlit
    import sys
    if "streamlit" in sys.modules:
        create_streamlit_app()
    else:
        main()